version: "3.9"

services:
  db1:
    image: mysql:latest
    container_name: Base-de-datos-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress1
    volumes:
      - db1_data:/var/lib/mysql

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db1:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wordpress1
    volumes:
      - wordpress1_data:/var/www/html
    depends_on:
      - db1

volumes:
  db1_data:
  wordpress1_data:
