version: "3.9"

services:
  db2:
    image: mysql:latest
    container_name: Base-de-datos-2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress2
    volumes:
      - db2_data:/var/lib/mysql

  wordpress2:
    image: wordpress:latest
    container_name: wordpress-2
    restart: always
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: db2:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wordpress2
    volumes:
      - wordpress2_data:/var/www/html
    depends_on:
      - db2

volumes:
  db2_data:
  wordpress2_data:
